#Config file for appliances definitions
shift1:
  appliance_cls: ShiftApp
  params:
      duration: 90  #minutes
      base_load: 2  #power in kw

shift2:
  appliance_cls: ShiftApp
  params:
      duration: 120 
      base_load: 1.8

storage1:
  appliance_cls: StorageApp
  params:
    max_ch: 4 #kw
    max_disch: 3.6 #kw
    capacity: 14 #kwh
