#Config file for agent definitions
ag1:
  agent_cls: Agent
  params:
    load_id: ag1 # id of the load that is imported from GECAD
    pv_id: PV1
    delivery_time: '17:00'
  appliances:
    - shift2
  data_info:
    data_file: 'Dataset_gecad_changed.xlsx'
    data_proc_cls: GecadDataProcessor
  tariffs:
    tar_type: double_rate #flat, din
    flat_val: 0.1 #€/kwh
    double__rate_params:
      empty_start: 8
      empty_end: 22
      empty_val: 0.0615
      no_empty_val: 0.1393

ag2:
  agent_cls: Agent
  params:
    load_id: ag2
    pv_id: PV2
    delivery_time: '18:30'
  appliances:
    - shift1
  data_info:
    data_file: 'Dataset_gecad_changed.xlsx'
    data_proc_cls: GecadDataProcessor
  tariffs:
    tar_type: 'double_rate' #flat, din
    flat_val: 0.1 #€/kwh
    double__rate_params:
      empty_start: 8
      empty_end: 22
      empty_val: 0.0615
      no_empty_val: 0.1393

ag3:
  agent_cls: Agent
  params:
    load_id: ag3 # id of the load that is imported from GECAD
    pv_id: PV3
    delivery_time: '17:00'
  appliances:
    - shift1
  data_info:
    data_file: 'Dataset_gecad_changed.xlsx'
    data_proc_cls: GecadDataProcessor
  tariffs:
    tar_type: 'double_rate' #flat, din
    flat_val: 0.1 #€/kwh
    double__rate_params:
      empty_start: 8
      empty_end: 22
      empty_val: 0.0615
      no_empty_val: 0.1393
#
#
# ag4:
#   agent_cls: Agent
#   params:
#     load_id: ag4 # id of the load that is imported from GECAD
#     pv_id: PV4
#     delivery_time: '17:00'
#   appliances:
#     - shift2
#   data_info:
#     data_file: 'Dataset_gecad_changed.xlsx'
#     data_proc_cls: GecadDataProcessor
#   tariffs:
#     tar_type: 'double_rate' #flat, din
#     flat_val: 0.1 #€/kwh
#     double__rate_params:
#       empty_start: 8
#       empty_end: 22
#       empty_val: 0.0915
#       no_empty_val: 0.1393
#
#
#
# ag5:
#   agent_cls: Agent
#   params:
#     load_id: ag5 # id of the load that is imported from GECAD
#     pv_id: PV5
#     delivery_time: '17:30'
#   appliances:
#     - shift1
#   data_info:
#     data_file: 'Dataset_gecad_changed.xlsx'
#     data_proc_cls: GecadDataProcessor
#   tariffs:
#     tar_type: 'double_rate' #flat, din
#     flat_val: 0.1 #€/kwh
#     double__rate_params:
#       empty_start: 8
#       empty_end: 22
#       empty_val: 0.115
#       no_empty_val: 0.1393
