tstep:
  max: 100000
  min: -1.0
  use: true
minutes:
  max: 1440
  min: -1.0
  use: true
sin:
  max: 1.0
  min: -1.0
  use: true
cos:
  max: 1.0
  min: -1.0
  use: true
gen0:
  max: Null
  min: -1.0
  use: true
gen1:
  max: Null
  min: -1.0
  use: true
gen2:
  max: Null
  min: -1.0
  use: true
gen3:
  max: Null
  min: -1.0
  use: true
gen4:
  max: Null
  min: -1.0
  use: true
gen5:
  max: Null
  min: -1.0
  use: true
gen6:
  max: Null
  min: -1.0
  use: true
gen7:
  max: Null
  min: -1.0
  use: true
gen8:
  max: Null
  min: -1.0
  use: true
gen9:
  max: Null
  min: -1.0
  use: true
gen10:
  max: Null
  min: -1.0
  use: true
gen11:
  max: Null
  min: -1.0
  use: true
gen12:
  max: Null
  min: -1.0
  use: true
load0:
  max: Null
  min: -1.0
  use: true
load1:
  max: Null
  min: -1.0
  use: true
load2:
  max: Null
  min: -1.0
  use: true
load3:
  max: Null
  min: -1.0
  use: true
load4:
  max: Null
  min: -1.0
  use: true
load5:
  max: Null
  min: -1.0
  use: true
load6:
  max: Null
  min: -1.0
  use: true
load7:
  max: Null
  min: -1.0
  use: true
load8:
  max: Null
  min: -1.0
  use: true
load9:
  max: Null
  min: -1.0
  use: true
load10:
  max: Null
  min: -1.0
  use: true
load11:
  max: Null
  min: -1.0
  use: true
load12:
  max: Null
  min: -1.0
  use: true
delta0:
  max: Null
  min: Null
  use: false
delta1:
  max: Null
  min: Null
  use: false
delta2:
  max: Null
  min: Null
  use: false
delta3:
  max: Null
  min: Null
  use: false
delta4:
  max: Null
  min: Null
  use: false
delta5:
  max: Null
  min: Null
  use: false
delta6:
  max: Null
  min: Null
  use: false
delta7:
  max: Null
  min: Null
  use: false
delta8:
  max: Null
  min: Null
  use: false
delta9:
  max: Null
  min: Null
  use: false
delta10:
  max: Null
  min: Null
  use: false
delta11:
  max: Null
  min: Null
  use: false
delta12:
  max: Null
  min: Null
  use: false
excess0:
  max: Null
  min: Null
  use: true
excess1:
  max: Null
  min: Null
  use: true
excess2:
  max: Null
  min: Null
  use: true
excess3:
  max: Null
  min: Null
  use: true
excess4:
  max: Null
  min: Null
  use: true
excess5:
  max: Null
  min: Null
  use: true
excess6:
  max: Null
  min: Null
  use: true
excess7:
  max: Null
  min: Null
  use: true
excess8:
  max: Null
  min: Null
  use: true
excess9:
  max: Null
  min: Null
  use: true
excess10:
  max: Null
  min: Null
  use: true
excess11:
  max: Null
  min: Null
  use: true
excess12:
  max: Null
  min: Null
  use: true
y:
  max: 1.0
  min: -1.0
  use: true
y_1:
  max: 1.0
  min: -1.0
  use: true
y_s:
  max: Null
  min: -1.0
  use: true
tar_buy:
  max: 1.0
  min: -1.0
  use: true
tar_buy0:
  max: 1.0
  min: -1.0
  use: true
E_prof_rem:
  max: 100.0
  min: 0
  use: true
