local-debug:
  file_ag_conf: 'agents_config.yaml'
  file_apps_conf: 'apps_config.yaml'
  file_scene_conf: 'scenario_config.yaml'
  file_prob_conf: problem_config.yaml'
  file_vars: 'state_vars.yaml'
  file_experiment: 'experiment_config.yaml'

fcul1:
  file_ag_conf: 'agents_config.yaml'
  file_apps_conf: 'apps_config.yaml'
  file_scene_conf: 'scenario_config.yaml'
  file_prob_conf: problem_config.yaml'
  file_vars: 'state_vars.yaml'
  file_experiment: 'experiment_config.yaml'

fcul1-debug:
  file_ag_conf: 'agents_config.yaml'
  file_apps_conf: 'apps_config.yaml'
  file_scene_conf: 'scenario_config.yaml'
  file_prob_conf: problem_config.yaml'
  file_vars: 'state_vars.yaml'
  file_experiment: 'experiment_config.yaml'
