minutes:
  max: 1440
  min: -1.0
  use: true
sin:
  max: 1.0
  min: -1.0
  use: true
cos:
  max: 1.0
  min: -1.0
  use: true
load0:
  max: 100
  min: -1.0
  use: true
gen0:
  max: 100
  min: -1.0
  use: true
excess0:
  max: 100
  min: -1.0
  use: true
tar_buy:
  max: 1.0
  min: -1.0
  use: true
E_prof_rem:
  max: 100.0
  min: 0.0
  use: true
y_s:
  max: 20
  min: 0.0
  use: true
pv_sum:
  max: 1000
  min: 0
  use: true
